// Mocks generated by Mockito 5.4.6 from annotations
// in string_calculator/test/features/string_calculator/domain/usecases/calculate_string_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:string_calculator/features/string_calculator/domain/entities/calculation_result.dart'
    as _i2;
import 'package:string_calculator/features/string_calculator/domain/repositories/calculator_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCalculationResult_0 extends _i1.SmartFake
    implements _i2.CalculationResult {
  _FakeCalculationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CalculatorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculatorRepository extends _i1.Mock
    implements _i3.CalculatorRepository {
  MockCalculatorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CalculationResult> add(String? numbers) =>
      (super.noSuchMethod(
            Invocation.method(#add, [numbers]),
            returnValue: _i4.Future<_i2.CalculationResult>.value(
              _FakeCalculationResult_0(
                this,
                Invocation.method(#add, [numbers]),
              ),
            ),
          )
          as _i4.Future<_i2.CalculationResult>);
}
